image: node:20-alphine

stages: 
  - build
  - deploy

build: 
  stage: build
  script: 
    - npm install
    - npm run build 
  artifacts:
    paths:
      - frontend/.next
    only: 
      - main

pages: 
  stage: deploy
  script: 
    - npm install
    - npm run build 
    - npm run export
  artifacts:
    paths:
      - frontend/out
    only: 
      - main